# Generated by Django 6.0.2 on 2026-02-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='joining_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=100, null=True),
        ),
    ]
