# Generated by Django 6.0.2 on 2026-02-08 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0002_employeemodel_joining_date_employeemodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('month', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=100, null=True)),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_salary', to='form_app.employeemodel')),
            ],
        ),
    ]
